# Generated by Django 4.1.7 on 2023-03-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_driver_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license',
            field=models.ImageField(null=True, upload_to='licenses/', verbose_name='Лицензия'),
        ),
    ]
