# Generated by Django 4.1.7 on 2023-03-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_driver_email_alter_driver_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='image',
            field=models.ImageField(null=True, upload_to='trucks/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license',
            field=models.ImageField(null=True, upload_to='licenses/'),
        ),
    ]
