# Generated by Django 4.1.7 on 2023-03-28 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_truck_image_alter_driver_license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='company',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='assigned_driver',
        ),
        migrations.AddField(
            model_name='shipment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
