# Generated by Django 4.1.7 on 2023-03-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_shipment_phone_number_alter_shipment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ф.И.О'),
        ),
    ]
