# Generated by Django 4.1.7 on 2023-03-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_driver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='license',
        ),
        migrations.AddField(
            model_name='driver',
            name='license_back',
            field=models.ImageField(null=True, upload_to='licenses_back/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_front',
            field=models.ImageField(null=True, upload_to='licenses_front/'),
        ),
    ]
