# Generated by Django 4.1.7 on 2023-03-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_truck_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='status',
        ),
    ]
